env:
  browser: true
  commonjs: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'react-app'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console:
    - warn
